syntax = "proto3";

package jp.co.sony.hes.ssh.controldevice.v1;

message ConfirmSigninRequest {
  bytes auth_data = 1;
}

message ConfirmSigninResponse {
  bool success = 1;
}

message ConfirmKeysRequest {
  string session_id = 1;
  bytes key_data = 2;
}

message ConfirmKeysResponse {}

message GetSessionRandomRequest {
  string session_id = 1;
}

message GetSessionRandomResponse {
  bytes session_random = 1;
  bytes auth_token = 2;
  string session_id = 3;
}

message StartNotifyStatesRequest {
  string session_id = 1;
}

service ControlDeviceService {
  rpc ConfirmSignin(ConfirmSigninRequest) returns (ConfirmSigninResponse);
  rpc ConfirmKeys(ConfirmKeysRequest) returns (ConfirmKeysResponse);
  rpc GetSessionRandom(GetSessionRandomRequest) returns (GetSessionRandomResponse);
}
